version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  back:
    image: denoland/deno
    restart: "no"
    #entrypoint: "ls /www/back"
    entrypoint: "deno run --allow-net --allow-read --allow-write --watch /www/back/src/server.ts"
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./back:/www/back
      - ./shared:/www/shared
